blog/urls.py
from django.urls import path
from .views import index, about, add_post, post_list, post_detail, post_edit, post_delete


app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('post/add/', add_post, name='add_post'),
    path('post/', post_list, name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),

]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from myblog import settings

from blog.views import root

urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.page_not_found'
handler500 = 'blog.views.server_error'




"""
127.0.0.1:8005/          = mysite.com/              ''
127.0.0.1:8005/blog/     = mysite.com/blog/         'blog/'
127.0.0.1:8005/blog/     = mysite.com/blog/about/
"""

users/urls.py
from django.urls import path
from .views import register, log_in, log_out, user_detail, change_password

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>/', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.CharField(max_length=50, verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст поста')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Опубликовано', editable=False)
    image = models.ImageField(upload_to='posts/', null=True, verbose_name='Изображение')

    class Meta:
        # Имя таблицы в единственном числе
        verbose_name = 'Пост'
        # Имя таблици во множественном числе
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20, verbose_name="Televon")
    citi = models.CharField(max_length=100, verbose_name='Gorod')
    image = models.ImageField(upload_to='users/', null=True, verbose_name='Izobrachenie')

blog/forms.py
from django import forms
from .models import Post

# class PostForm(forms.Form):
#     author = forms.CharField(max_length=50, label='Автор')
#     title = forms.CharField(max_length=200, label='Заголовок')
#     text = forms.CharField(label='Текст поста', widget=forms.Textarea())

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'image']

users/forms.py
from django import forms
from django.contrib.auth import get_user_model

#Получения тякущей модели пользователя
User = get_user_model()

#Создание формы регистрации пользователя
class UserRegistrationFrom(forms.ModelForm):
    #Создание дополнительного поля пороля для повторного ввода при регистрации
    password2 = forms.CharField(label='Повторить пароль', widget=forms.PasswordInput)

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совподают!')
        return cleaned_data['password2']

    class Meta:
        model = User
        fields = ('username', 'password',
                  'first_name', 'last_name', 'email',
                  'phone', 'citi')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse

from .forms import PostForm
from .models import Post


"""
FBV - Function based views (Предстовления основоных на функциях)
CBV - Class based views (Предстовление основаных на классах)
"""

def root(request):
    return render(request, template_name='blog/index.html')


def index(request):
    return render(request, template_name='blog/index.html')


def about(request):
    context = {
        'name': 'Дмитрий',
        'lastname': 'Горим',
        'email': 'd.gorin@mail.ru',
        'title': 'О сайте'
    }
    return render(request, template_name='blog/about.html', context=context)

def add_post(request):
    if request.method == "GET":
        form = PostForm()
        context = {
            'form': form,
            'title': 'Добовления поста'
        }
        return render(request, template_name='blog/add_post.html', context=context)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

        return index(request)


def post_list(request):
    # Получаем все объект модели Post
    posts = Post.objects.all()
    context = {
        'title': 'Посты',
        'posts': posts
    }
    return render(request, template_name='blog/posts.html', context=context)


def post_detail(request, pk):
    # Получаем объект с задоным pk(ключем)
    post = get_object_or_404(Post, pk=pk)
    context = {
        'title': 'Информация о посте',
        'post': post
    }
    return render(request, template_name='blog/post_detail.html', context=context)


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            return post_list(request)

    else:
        form = PostForm(instance=post)

    context = {
        'forma': form,
        'title': 'Редактировать пост'
    }
    return render(request, template_name='blog/post_edit.html', context=context)


def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:post_list')
    return render(request, template_name='blog/post_delete.html', context={'post': post})

def page_not_found(request, exception):
    return render(request, 'blog/404.html', status=404)

def server_error(request):
    return render(request, 'blog/500.html', status=500)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

from myblog.settings import LOGIN_REDIRECT_URL
from .forms import UserRegistrationFrom


def register(request):
    # Если ножали кнопку регистрации (это метод POST)
    if request.method == 'POST':
        # Создаем объект формы с данными из запроса
        user_form = UserRegistrationFrom(request.POST)
        # Валидация формы (правильность введение данных)
        if user_form.is_valid():
            # Создание объекта с полями формы (без сохранения в БД)
            new_user = user_form.save(commit=False)
            # Хэширование пароля пользователя
            new_user.set_password(user_form.cleaned_data['password'])
            # Сохранения пользователя в БД
            new_user.save()
            context = {'title': 'Успешная регистрация', 'new_user': new_user}
            return render(request, template_name='users/register_done.html', context=context)

    # Метод GET - отрисовка страницы регистрации
    user_form = UserRegistrationFrom()
    context = {'title': 'Регистрация', 'register_form': user_form}
    return render(request, template_name='users/register.html', context=context)

def log_in(request):
    #Создания формыаутификации
    form = AuthenticationForm(request, request.POST)
    #Проверка формы
    if form.is_valid():
        #Получение логина и пароля из формы
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        #Аутификация пользователя (проверка наличия пользователя и пароля)
        user = authenticate(username=username, password=password)
        if user:
            #
            login(request, user)
            #
            url = request.GET.get('next', LOGIN_REDIRECT_URL)
            return redirect(url)
    context = {'form': form}
    return render(request, template_name='users/login.html', context=context)


def log_out(request):
    logout(request)
    return redirect('blog:index')


def user_detail(request, pk):
    pass

def change_password(request):
    pass

blog/templates/blog/501.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<h2> Это HTML-страничка о сайте </h2>
<p>Автор - {{name}} {{lastname}}</p>
<p>Эл. Почта - {{email}}</p>
{% endblock content %}

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% block content %}
<h2> Добавить новый пост </h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Создать пост </button>
</form>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<!--<img src="{% static 'img/image.png' %}"/>-->
Здесь будет хедер с меню
<hr>
{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<a href="{% url 'blog:post_list' %}">Посты</a>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content %}

<h2>Удалить пост?</h2>
<h3>Информация о посте № {{post.id}}</h3>
<hr>
<p>Автор - {{post.author}}</p>
<p>Название - {{post.title}}</p>
<p>Текст поста:</p>
<p>{{post.text}}</p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}

<br>
<p>Создать: {{post.created_at}}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'blog:post_list' %}">
        <button type="button" class="btn btn-primary">Отменить</button>
    </a>
</form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2> Информация о посте № {{post.id}} </h2>
<hr>
<p> Автор - {{post.author}} </p>
<p> Название - {{post.title}} </p>
<p> Текст поста: </p>
<p> {{post.text}} </p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}
<br>
<p> Создан: {{post.created_at}} </p>
<div>
    <a href="{% url 'blog:post_edit' pk=post.id %}" class="btn btn-primary">Редоктировать</a>
    <form action="{% url 'blog:post_delete' pk=post.id %}" method="get" style="display:inline">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>
<!--<button type="submit"> Редоктировать </button>-->
<!--<br>-->
<!--<button type="submit"> Удалить </button>-->
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h2> Редактировать пост </h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Редактировать </button>
</form>
{% endblock content %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h2> Список постов </h2>
{% for post in posts %}
    <p>{{post.author}}: <a href="{% url 'blog:post_detail' pk=post.id %}"> {{post.title}}</a></p>
    <p>{{post.text}}</p>
    <p>{{post.created_at}}</p>
    <br>
{% endfor %}

{% endblock content %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Аккаунт</a>
    <ul class="dropdown-menu">
      {% if not user.is_authenticated %}
      <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
      <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
      <li><hr class="dropdown-divider"></li>
      {% endif %}
      {% if user.is_authenticated %}
      <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйте</a></li>
      <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username}}</a></li>
      {% endif %}
    </ul>
  </li>
</ul>

{% block content %}

{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}

<h2>Пожалуйстф войдите на сайт
</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>

{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}

<h2>Регистрация пользователя</h2>
<form method="post">
    {% csrf_token %}
    {{ register_form }}


    <button type="submit">Зарегистрироваться</button>

</form>


{% endblock content %}

users/templates/users/register_done.html
{% extends 'users/base.html' %}

{% block content %}

<h2> Пользователь {{ new_user.username }} успешно зарегистрирован </h2>

<p>Имя - {{ new_user.first_name }}</p>
<p>Фамилия - {{ new_user.last_name }}</p>
<p>Email - {{ new_user.email }}</p>
<p>Телефон - {{ new_user.phone }}</p>

{% endblock content %}